Handle tempest resources clean-up
Three levels of clean-up is implemented to facilitate different
scenarios:
1. quick clean-up that removes resources created by tempest tests.
This can be used in-between test runs.
2. extensive clean-up that, in addition to 1, also removes test
accounts, project, and the associated network resources. This is
used after charm refresh where the previous test accounts becomes
obsoletes.
3. full cleanup that, in addition to 1 and 2, deletes the testing
domain, user, and project created through keystone relation. This
is used at the initial stage of keystone relation joins to get
a fresh env.

Change-Id: If172e9dde0e04c53849d7a0b30fc27f62c5bdbd9

diff --git a/charms/tempest-k8s/src/templates/tempest-run-wrapper.j2 b/charms/tempest-k8s/src/templates/tempest-run-wrapper.j2
--- a/charms/tempest-k8s/src/templates/tempest-run-wrapper.j2
+++ b/charms/tempest-k8s/src/templates/tempest-run-wrapper.j2
@@ -15,6 +15,7 @@ echo ":: discover-tempest-config" >> "$TMP_FILE"
 if discover-tempest-config --test-accounts "$TEMPEST_TEST_ACCOUNTS" --out "$TEMPEST_CONF" >> "$TMP_FILE" 2>&1; then
     echo ":: tempest run" >> "$TMP_FILE"
     tempest run --workspace "$TEMPEST_WORKSPACE" "$@" >> "$TMP_FILE" 2>&1
+    python3 "$TEMPEST_HOME/cleanup.py"
 else
     echo ":: skipping tempest run because discover-tempest-config had errors" >> "$TMP_FILE"
 fi
@@ -27,6 +28,14 @@ sed $'s/\033\[[0-9;]*m//g' -i "$TMP_FILE"
 # This ensures we don't have issues with logging libs pushing partial files,
 # if we were to stream to the final output.
 mv "$TMP_FILE" "$TEMPEST_OUTPUT"
+
+SUMMARY="$(awk '/^Totals$/,/Sum of execute/ { print }' < "$TEMPEST_OUTPUT")"
+if [[ -n "$SUMMARY" ]]; then
+    echo "$SUMMARY"
+else
+    echo "Error running the tests, please view the log file"
+    exit 1
+fi
 
 SUMMARY="$(awk '/^Totals$/,/Sum of execute/ { print }' < "$TEMPEST_OUTPUT")"
 if [[ -n "$SUMMARY" ]]; then
